In [84]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sklearn.datasets

**Loading the dataset in a Pandas Dataframe**

In [85]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [86]:
breast_cancer

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [87]:
X = breast_cancer.data
Y = breast_cancer.target

In [88]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [89]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [90]:
print(X.shape, Y.shape)

(569, 30) (569,)


In [91]:
df = pd.DataFrame(breast_cancer.data, columns = breast_cancer.feature_names)

In [92]:
df['class'] =  breast_cancer.target

In [93]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  class  
0                  0.2654          0.4601                  0.11890      0  
1                  0.1860          0.2750                  0.08902      0  
2                  0.2430          0.3613                  0.08758      0  
3                  0.2575          0.6638                  0.17300      0  
4                  0.1625          0.2364                  0.07678   

In [94]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [95]:
df.groupby('class').mean()
#0 = malignant
#1 = benign

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

**Train and Test Data Split**

In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=42)
#stratify --> for correct distribution of data as of the original data
#random_state --> specific split of data, each value of random_state splits the data differently

In [97]:
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (455,) (114,)


In [98]:
print(X_train.mean(), X_test.mean(), X.mean())

61.21359590991941 64.59323844011696 61.890712339519624


## **Logistic Regression**

In [99]:
#import logistic regression from sklearn
from sklearn.linear_model import LogisticRegression

In [100]:
classifier = LogisticRegression()

In [101]:
#training the model on training data
classifier.fit(X_train, Y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [102]:
#import accuracy_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [103]:
#prediction on test_data
prediction = classifier.predict(X_test)
accuracy = accuracy_score(Y_test, prediction)

In [104]:
# Creating accuracy dictionary
accuracy_dict = {}
accuracy_dict['Logistic Regression'] = round((accuracy * 100),2)

In [105]:
print(f'Accuracy: {accuracy}')

Accuracy: 0.9473684210526315


In [106]:
accuracy_dict

{'Logistic Regression': 94.74}

In [107]:
# Confusion Matrix
conf_matrix = confusion_matrix(Y_test, prediction)
print(f'Confusion Matrix:\n{conf_matrix}')

Confusion Matrix:
[[38  4]
 [ 2 70]]


In [108]:
# Classification Report
class_report = classification_report(Y_test, prediction)
print(f'Classification Report:\n{class_report}')

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.90      0.93        42
           1       0.95      0.97      0.96        72

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



## **Support Vector Machine**

In [109]:
from sklearn.svm import SVC

In [110]:
# Initialize the model
model = SVC(kernel='linear')

In [111]:
# Train the model
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [112]:
# Predictions
prediction = model.predict(X_test)

In [113]:
# Accuracy
accuracy = accuracy_score(Y_test, prediction)
print(f'Accuracy: {accuracy}')

Accuracy: 0.956140350877193


In [114]:
accuracy_dict['SVM'] = round(accuracy * 100, 2)

In [115]:
# Confusion Matrix
conf_matrix = confusion_matrix(Y_test, prediction)
print(f'Confusion Matrix:\n{conf_matrix}')

Confusion Matrix:
[[38  4]
 [ 1 71]]


In [116]:
# Classification Report
class_report = classification_report(Y_test, prediction)
print(f'Classification Report:\n{class_report}')

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.90      0.94        42
           1       0.95      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



## **k-Nearest Neighbors**

In [117]:
from sklearn.neighbors import KNeighborsClassifier

In [118]:
# Initialize the model
k = 99  # Choosing k=99 for this example
model = KNeighborsClassifier(n_neighbors=k)

In [119]:
# Train the model
model.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=99)

In [120]:
# Predictions
prediction = model.predict(X_test)

In [121]:
# Accuracy
accuracy = accuracy_score(Y_test, prediction)
print(f'Accuracy: {accuracy}')

Accuracy: 0.9210526315789473


In [122]:
accuracy_dict['kNN-99'] = round(accuracy * 100, 2)

In [123]:
# Confusion Matrix
conf_matrix = confusion_matrix(Y_test, prediction)
print(f'Confusion Matrix:\n{conf_matrix}')

Confusion Matrix:
[[35  7]
 [ 2 70]]


In [124]:
# Classification Report
class_report = classification_report(Y_test, prediction)
print(f'Classification Report:\n{class_report}')

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.83      0.89        42
           1       0.91      0.97      0.94        72

    accuracy                           0.92       114
   macro avg       0.93      0.90      0.91       114
weighted avg       0.92      0.92      0.92       114



## **Decision Tree**

In [125]:
from sklearn.tree import DecisionTreeClassifier

In [126]:
# Initialize the model
model = DecisionTreeClassifier(random_state=42)

In [127]:
# Train the model
model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [128]:
# Predictions
prediction = model.predict(X_test)

In [129]:
# Accuracy
accuracy = accuracy_score(Y_test, prediction)
print(f'Accuracy: {accuracy}')

Accuracy: 0.9122807017543859


In [130]:
accuracy_dict['DT-42'] = round(accuracy * 100, 2)

In [131]:
# Confusion Matrix
conf_matrix = confusion_matrix(Y_test, prediction)
print(f'Confusion Matrix:\n{conf_matrix}')

Confusion Matrix:
[[39  3]
 [ 7 65]]


In [132]:
# Classification Report
class_report = classification_report(Y_test, prediction)
print(f'Classification Report:\n{class_report}')

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.93      0.89        42
           1       0.96      0.90      0.93        72

    accuracy                           0.91       114
   macro avg       0.90      0.92      0.91       114
weighted avg       0.92      0.91      0.91       114



## **Random Forest**

In [133]:
from sklearn.ensemble import RandomForestClassifier

In [134]:
# Initialize the model
model = RandomForestClassifier(random_state=42)

In [135]:
# Train the model
model.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [136]:
# Predictions
prediction = model.predict(X_test)

In [137]:
# Accuracy
accuracy = accuracy_score(Y_test, prediction)
print(f'Accuracy: {accuracy}')

Accuracy: 0.956140350877193


In [138]:
accuracy_dict['RF'] = round(accuracy * 100, 2)

In [139]:
# Confusion Matrix
conf_matrix = confusion_matrix(Y_test, prediction)
print(f'Confusion Matrix:\n{conf_matrix}')

Confusion Matrix:
[[39  3]
 [ 2 70]]


In [140]:
# Classification Report
class_report = classification_report(Y_test, prediction)
print(f'Classification Report:\n{class_report}')

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        42
           1       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



## **Accuracy Comparison**

In [141]:
accuracy_dict

{'Logistic Regression': 94.74,
 'SVM': 95.61,
 'kNN-99': 92.11,
 'DT-42': 91.23,
 'RF': 95.61}

In [142]:
import plotly.graph_objects as go

In [143]:
# Define the data
models = list(accuracy_dict.keys())
accuracy_scores = list(accuracy_dict.values())

# Create a bar graph
fig = go.Figure(data=[go.Bar(
    x=models,
    y=accuracy_scores,
    text=accuracy_scores,
    textposition='auto',
)])

# Customize layout
fig.update_layout(
    title='Accuracy Scores of Different Models',
    xaxis_title='Models',
    yaxis_title='Accuracy (%)',
    yaxis=dict(range=[0, 100]),  # set the range of y-axis
)

# Show the plot
fig.show()